services:
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - digifor-network

  seed:
    build: .
    depends_on:
      - app
    command: ["python", "-m", "app.auth.seed"]
    restart: always
    networks:
      - digifor-network

networks:
  digifor-network:
    external: true
